MPESA_CONSUMER_KEY: 'w1ZSo6QoLqeGcixixP5iO6WLMPiizfjm'
MPESA_CONSUMER_SECRET: 'n3yz645gjAHvNAUW'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'password: Safaricom999!*!'
CALLBACK_URL: 'https://0dfd-102-217-64-20.ngrok-free.app'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"